// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: operationcontainer.proto

package OperationContainer

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "buf.build/gen/go/service-hub/loggable/protocolbuffers/go/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN     Status = 0 // Use when the status of the operation is not known.
	Status_PENDING     Status = 1 // Use when an operation has been scheduled and is waiting to be picked up and processed.
	Status_IN_PROGRESS Status = 2 // Use when an operation has been picked up by a processor and is being processed.
	Status_SUCCEEDED   Status = 3 // Use when an operation has run successfully.
	Status_FAILED      Status = 4 // Use when an operation had a catastrophic failure and can't be completed.
	Status_CANCELED    Status = 5 // Use when an operation was intentionally stopped before completion.
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "IN_PROGRESS",
		3: "SUCCEEDED",
		4: "FAILED",
		5: "CANCELED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":     0,
		"PENDING":     1,
		"IN_PROGRESS": 2,
		"SUCCEEDED":   3,
		"FAILED":      4,
		"CANCELED":    5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_operationcontainer_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_operationcontainer_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_operationcontainer_proto_rawDescGZIP(), []int{0}
}

type CreateOperationStatusRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationName       string                 `protobuf:"bytes,1,opt,name=operationName,proto3" json:"operationName,omitempty"`
	EntityId            string                 `protobuf:"bytes,2,opt,name=entityId,proto3" json:"entityId,omitempty"`
	ExpirationTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expirationTimestamp,proto3" json:"expirationTimestamp,omitempty"`
	OperationId         string                 `protobuf:"bytes,4,opt,name=operationId,proto3" json:"operationId,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOperationStatusRequest) Reset() {
	*x = CreateOperationStatusRequest{}
	mi := &file_operationcontainer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationStatusRequest) ProtoMessage() {}

func (x *CreateOperationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operationcontainer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationStatusRequest.ProtoReflect.Descriptor instead.
func (*CreateOperationStatusRequest) Descriptor() ([]byte, []int) {
	return file_operationcontainer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOperationStatusRequest) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *CreateOperationStatusRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateOperationStatusRequest) GetExpirationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return nil
}

func (x *CreateOperationStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type UpdateOperationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=OperationContainer.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperationStatusRequest) Reset() {
	*x = UpdateOperationStatusRequest{}
	mi := &file_operationcontainer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperationStatusRequest) ProtoMessage() {}

func (x *UpdateOperationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operationcontainer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOperationStatusRequest) Descriptor() ([]byte, []int) {
	return file_operationcontainer_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOperationStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *UpdateOperationStatusRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type GetOperationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationStatusRequest) Reset() {
	*x = GetOperationStatusRequest{}
	mi := &file_operationcontainer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationStatusRequest) ProtoMessage() {}

func (x *GetOperationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operationcontainer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOperationStatusRequest) Descriptor() ([]byte, []int) {
	return file_operationcontainer_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationStatusRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=OperationContainer.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationStatusResponse) Reset() {
	*x = GetOperationStatusResponse{}
	mi := &file_operationcontainer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationStatusResponse) ProtoMessage() {}

func (x *GetOperationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operationcontainer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOperationStatusResponse) Descriptor() ([]byte, []int) {
	return file_operationcontainer_proto_rawDescGZIP(), []int{3}
}

func (x *GetOperationStatusResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

var File_operationcontainer_proto protoreflect.FileDescriptor

const file_operationcontainer_proto_rawDesc = "" +
	"\n" +
	"\x18operationcontainer.proto\x12\x12OperationContainer\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bbuf/validate/validate.proto\x1a\x0fproto/log.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n" +
	"\x1cCreateOperationStatusRequest\x12-\n" +
	"\roperationName\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\roperationName\x12#\n" +
	"\bentityId\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bentityId\x12V\n" +
	"\x13expirationTimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x05\xb2\x01\x02@\x01R\x13expirationTimestamp\x12)\n" +
	"\voperationId\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\voperationId\"}\n" +
	"\x1cUpdateOperationStatusRequest\x12)\n" +
	"\voperationId\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\voperationId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.OperationContainer.StatusR\x06status\"F\n" +
	"\x19GetOperationStatusRequest\x12)\n" +
	"\voperationId\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\voperationId\"P\n" +
	"\x1aGetOperationStatusResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.OperationContainer.StatusR\x06status*\\\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\r\n" +
	"\tSUCCEEDED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\f\n" +
	"\bCANCELED\x10\x052\xa7\x05\n" +
	"\x12OperationContainer\x12\xdb\x01\n" +
	"\x15CreateOperationStatus\x120.OperationContainer.CreateOperationStatusRequest\x1a\x16.google.protobuf.Empty\"x\x92AO\x12\x1dCreate a new Operation Status\x1a.This operation creates a new operation status.\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/operation/{operationId}\x12\xdc\x01\n" +
	"\x12GetOperationStatus\x12-.OperationContainer.GetOperationStatusRequest\x1a..OperationContainer.GetOperationStatusResponse\"g\x92AA\x12\x14Get Operation Status\x1a)This operation gets the operation status.\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/operation/{operationId}\x12\xd3\x01\n" +
	"\x15UpdateOperationStatus\x120.OperationContainer.UpdateOperationStatusRequest\x1a\x16.google.protobuf.Empty\"p\x92AG\x12\x17Update Operation Status\x1a,This operation updates the operation status.\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/v1/operation/{operationId}B\xbe\x01\n" +
	"\x16com.OperationContainerB\x17OperationcontainerProtoP\x01Z#github.com/Azure/OperationContainer\xa2\x02\x03OXX\xaa\x02\x12OperationContainer\xca\x02\x12OperationContainer\xe2\x02\x1eOperationContainer\\GPBMetadata\xea\x02\x12OperationContainerb\x06proto3"

var (
	file_operationcontainer_proto_rawDescOnce sync.Once
	file_operationcontainer_proto_rawDescData []byte
)

func file_operationcontainer_proto_rawDescGZIP() []byte {
	file_operationcontainer_proto_rawDescOnce.Do(func() {
		file_operationcontainer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operationcontainer_proto_rawDesc), len(file_operationcontainer_proto_rawDesc)))
	})
	return file_operationcontainer_proto_rawDescData
}

var file_operationcontainer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_operationcontainer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_operationcontainer_proto_goTypes = []any{
	(Status)(0),                          // 0: OperationContainer.Status
	(*CreateOperationStatusRequest)(nil), // 1: OperationContainer.CreateOperationStatusRequest
	(*UpdateOperationStatusRequest)(nil), // 2: OperationContainer.UpdateOperationStatusRequest
	(*GetOperationStatusRequest)(nil),    // 3: OperationContainer.GetOperationStatusRequest
	(*GetOperationStatusResponse)(nil),   // 4: OperationContainer.GetOperationStatusResponse
	(*timestamppb.Timestamp)(nil),        // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 6: google.protobuf.Empty
}
var file_operationcontainer_proto_depIdxs = []int32{
	5, // 0: OperationContainer.CreateOperationStatusRequest.expirationTimestamp:type_name -> google.protobuf.Timestamp
	0, // 1: OperationContainer.UpdateOperationStatusRequest.status:type_name -> OperationContainer.Status
	0, // 2: OperationContainer.GetOperationStatusResponse.status:type_name -> OperationContainer.Status
	1, // 3: OperationContainer.OperationContainer.CreateOperationStatus:input_type -> OperationContainer.CreateOperationStatusRequest
	3, // 4: OperationContainer.OperationContainer.GetOperationStatus:input_type -> OperationContainer.GetOperationStatusRequest
	2, // 5: OperationContainer.OperationContainer.UpdateOperationStatus:input_type -> OperationContainer.UpdateOperationStatusRequest
	6, // 6: OperationContainer.OperationContainer.CreateOperationStatus:output_type -> google.protobuf.Empty
	4, // 7: OperationContainer.OperationContainer.GetOperationStatus:output_type -> OperationContainer.GetOperationStatusResponse
	6, // 8: OperationContainer.OperationContainer.UpdateOperationStatus:output_type -> google.protobuf.Empty
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_operationcontainer_proto_init() }
func file_operationcontainer_proto_init() {
	if File_operationcontainer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operationcontainer_proto_rawDesc), len(file_operationcontainer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operationcontainer_proto_goTypes,
		DependencyIndexes: file_operationcontainer_proto_depIdxs,
		EnumInfos:         file_operationcontainer_proto_enumTypes,
		MessageInfos:      file_operationcontainer_proto_msgTypes,
	}.Build()
	File_operationcontainer_proto = out.File
	file_operationcontainer_proto_goTypes = nil
	file_operationcontainer_proto_depIdxs = nil
}
