/*
 * operationcontainer.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

type OperationContainerGoalState string

// List of OperationContainerGoalState
const (
	UNKNOWN_OperationContainerGoalState OperationContainerGoalState = "UNKNOWN"
	PENDING_OperationContainerGoalState OperationContainerGoalState = "PENDING"
	IN_PROGRESS_OperationContainerGoalState OperationContainerGoalState = "IN_PROGRESS"
	COMPLETED_OperationContainerGoalState OperationContainerGoalState = "COMPLETED"
	FAILED_OperationContainerGoalState OperationContainerGoalState = "FAILED"
	CANCELLED_OperationContainerGoalState OperationContainerGoalState = "CANCELLED"
)
