/*
 * operationcontainer.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

type OperationContainerStatus string

// List of OperationContainerStatus
const (
	UNKNOWN_OperationContainerStatus     OperationContainerStatus = "UNKNOWN"
	PENDING_OperationContainerStatus     OperationContainerStatus = "PENDING"
	IN_PROGRESS_OperationContainerStatus OperationContainerStatus = "IN_PROGRESS"
	COMPLETED_OperationContainerStatus   OperationContainerStatus = "COMPLETED"
	FAILED_OperationContainerStatus      OperationContainerStatus = "FAILED"
	CANCELLED_OperationContainerStatus   OperationContainerStatus = "CANCELLED"
)
