/*
 * operationcontainer.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

type OperationContainerGetOperationStatusResponse struct {
	GoalState *OperationContainerGoalState `json:"goalState,omitempty"`
}
