/*
 * operationcontainer.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

type OperationContainerHelloRequest struct {
	Name    string                     `json:"name,omitempty"`
	Age     int32                      `json:"age,omitempty"`
	Email   string                     `json:"email,omitempty"`
	Address *OperationContainerAddress `json:"address,omitempty"`
}
