// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Azure/OperationContainer/api/v1 (interfaces: OperationContainerClient)
//
// Generated by this command:
//
//	mockgen -package mock github.com/Azure/OperationContainer/api/v1 OperationContainerClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	OperationContainer "github.com/Azure/OperationContainer/api/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockOperationContainerClient is a mock of OperationContainerClient interface.
type MockOperationContainerClient struct {
	ctrl     *gomock.Controller
	recorder *MockOperationContainerClientMockRecorder
}

// MockOperationContainerClientMockRecorder is the mock recorder for MockOperationContainerClient.
type MockOperationContainerClientMockRecorder struct {
	mock *MockOperationContainerClient
}

// NewMockOperationContainerClient creates a new mock instance.
func NewMockOperationContainerClient(ctrl *gomock.Controller) *MockOperationContainerClient {
	mock := &MockOperationContainerClient{ctrl: ctrl}
	mock.recorder = &MockOperationContainerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationContainerClient) EXPECT() *MockOperationContainerClientMockRecorder {
	return m.recorder
}

// CreateOperationStatus mocks base method.
func (m *MockOperationContainerClient) CreateOperationStatus(arg0 context.Context, arg1 *OperationContainer.CreateOperationStatusRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOperationStatus", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperationStatus indicates an expected call of CreateOperationStatus.
func (mr *MockOperationContainerClientMockRecorder) CreateOperationStatus(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperationStatus", reflect.TypeOf((*MockOperationContainerClient)(nil).CreateOperationStatus), varargs...)
}

// GetOperationStatus mocks base method.
func (m *MockOperationContainerClient) GetOperationStatus(arg0 context.Context, arg1 *OperationContainer.GetOperationStatusRequest, arg2 ...grpc.CallOption) (*OperationContainer.GetOperationStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOperationStatus", varargs...)
	ret0, _ := ret[0].(*OperationContainer.GetOperationStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationStatus indicates an expected call of GetOperationStatus.
func (mr *MockOperationContainerClientMockRecorder) GetOperationStatus(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationStatus", reflect.TypeOf((*MockOperationContainerClient)(nil).GetOperationStatus), varargs...)
}

// UpdateOperationStatus mocks base method.
func (m *MockOperationContainerClient) UpdateOperationStatus(arg0 context.Context, arg1 *OperationContainer.UpdateOperationStatusRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOperationStatus", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperationStatus indicates an expected call of UpdateOperationStatus.
func (mr *MockOperationContainerClientMockRecorder) UpdateOperationStatus(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperationStatus", reflect.TypeOf((*MockOperationContainerClient)(nil).UpdateOperationStatus), varargs...)
}
